# Generated by Django 4.1.9 on 2025-01-12 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='photo',
            new_name='picture',
        ),
    ]
