# Generated by Django 4.1.9 on 2025-01-11 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField(max_length=10, unique=True, verbose_name='Номер')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_person_match', to='persons.person', unique=True, verbose_name='Человек')),
                ('cabinet', models.CharField(max_length=10, default='502ю', verbose_name='Кабинет')),
            ],
        ),
    ]
