# Generated by Django 4.1.9 on 2025-01-12 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_rename_photo_person_picture'),
        ('user_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_person_match', to='persons.person', unique=True, verbose_name='Человек'),
        ),
    ]
