# Generated by Django 4.1.9 on 2025-01-12 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0004_alter_queue_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queue',
            options={},
        ),
    ]
