# Generated by Django 4.1.9 on 2025-01-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0005_alter_queue_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='number',
            field=models.TextField(max_length=10, unique=True, verbose_name='Номер'),
        ),
    ]
